# -*- coding: utf-8 -*-
"""project 5 final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bL3T4JbkKJERAeeGQo0cfTOKAaNYqjC7

**PROJECT NO - 5**

# TellCo Telecom User Analytics

## Project Overview

This project analyzes TellCo telecom user behavior using
xDR data.

## Objectives

- User Overview Analysis
- User Engagement Analysis
- User Experience Analysis
- User Satisfaction Analysis

## Technologies

- Python
- Pandas
- NumPy
- Scikit-learn
- Matplotlib
- Seaborn
- MySQL
- GitHub Actions

## Machine Learning

The project uses:

- K-Means clustering
- PCA
- Regression models

## Best Current Regression Model

Hist Gradient Boosting

## Dashboard

The project includes a Streamlit dashboard for:

- User Overview
- Engagement
- Experience
- Satisfaction
- Model Results

## Submitted By

Rashika Singh

**Import Libraries**
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import warnings
warnings.filterwarnings("ignore")

print("Libraries imported successfully")

"""**Load Your Dataset**"""

df = pd.read_csv("tellco.csv")

"""**Display First 5 Records**"""

df.head()

"""**Display Last 5 Records**"""

df.tail()

"""**Number of Rows and Columns**"""

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.shape

"""**Dataset Information**"""

df.info()

"""**Data Types**"""

df.dtypes

data_types = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values
})

data_types

"""**Basic Statistical Analysis**"""

df.describe()

"""**For all columns including categorical:**"""

df.describe(include="all")

"""**Note: For the project, mean, median and dispersion are particularly important because the PDF asks for non-graphical univariate analysis**

**Missing Value Count and Missing percentage:**
"""

missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().mean().values * 100
    )
})

missing_report = missing_report.sort_values(
    "Missing_Count",
    ascending=False
)

missing_report

"""**Check Duplicate Records**"""

duplicate_count = df.duplicated().sum()

print("Duplicate records:", duplicate_count)

"""**Duplicate percentage:**"""

duplicate_percentage = (
    df.duplicated().mean() * 100
)

print(
    "Duplicate percentage:",
    duplicate_percentage
)

"""**Remove Duplicate Records**"""

df_clean = df.copy()

df_clean = df_clean.drop_duplicates()
print(
    "Duplicates after cleaning:",
    df_clean.duplicated().sum()
)

"""**Identify Numeric Columns**"""

numeric_columns = df_clean.select_dtypes(
    include=np.number
).columns.tolist()

numeric_columns

"""**Identify Categorical Columns**"""

categorical_columns = df_clean.select_dtypes(
    exclude=np.number
).columns.tolist()

categorical_columns

"""**Missing Value Treatment**

**Numeric columns**
"""

for col in numeric_columns:

    if df_clean[col].isnull().sum() > 0:

        mean_value = df_clean[col].mean()

        df_clean[col] = df_clean[col].fillna(
            mean_value
        )

"""**Categorical columns**"""

for col in categorical_columns:

    if df_clean[col].isnull().sum() > 0:

        mode_value = df_clean[col].mode()[0]

        df_clean[col] = df_clean[col].fillna(
            mode_value
        )

df_clean.isnull().sum().sum()

"""**Outlier Detection Using IQR**"""

outlier_report = []

for col in numeric_columns:

    Q1 = df_clean[col].quantile(0.25)

    Q3 = df_clean[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR

    upper_bound = Q3 + 1.5 * IQR

    outliers = (
        (df_clean[col] < lower_bound) |
        (df_clean[col] > upper_bound)
    )

    count = outliers.sum()

    percentage = (
        count / len(df_clean) * 100
    )

    outlier_report.append([
        col,
        Q1,
        Q3,
        IQR,
        lower_bound,
        upper_bound,
        count,
        percentage
    ])

"""**Create table:**"""

outlier_df = pd.DataFrame(
    outlier_report,
    columns=[
        "Variable",
        "Q1",
        "Q3",
        "IQR",
        "Lower_Bound",
        "Upper_Bound",
        "Outlier_Count",
        "Outlier_Percentage"
    ]
)

outlier_df

"""**outliers should be replaced with the corresponding variable mean.**

**Outlier Treatment**
"""

for col in numeric_columns:

    Q1 = df_clean[col].quantile(0.25)

    Q3 = df_clean[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR

    upper_bound = Q3 + 1.5 * IQR

    mean_value = df_clean[col].mean()

    mask = (
        (df_clean[col] < lower_bound) |
        (df_clean[col] > upper_bound)
    )

    df_clean.loc[mask, col] = mean_value

"""**Check Clean Dataset**"""

print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

print(
    "Missing values:",
    df_clean.isnull().sum().sum()
)

print(
    "Duplicates:",
    df_clean.duplicated().sum()
)

"""**Univariate Analysis**"""

univariate = pd.DataFrame()

for col in numeric_columns:

    s = df_clean[col]

    univariate.loc[col, "Mean"] = s.mean()
    univariate.loc[col, "Median"] = s.median()
    univariate.loc[col, "Std_Dev"] = s.std()
    univariate.loc[col, "Variance"] = s.var()
    univariate.loc[col, "Minimum"] = s.min()
    univariate.loc[col, "Maximum"] = s.max()
    univariate.loc[col, "Skewness"] = s.skew()
    univariate.loc[col, "Kurtosis"] = s.kurtosis()

univariate

"""**`Histogram: For session duration `**"""

plt.figure(figsize=(10,6))

plt.hist(
    df_clean["Dur. (ms)"],
    bins=40
)

plt.title("Distribution of Session Duration")

plt.xlabel("Duration (ms)")

plt.ylabel("Frequency")

plt.show()

"""**Boxplot**"""

plt.figure(figsize=(10,5))

sns.boxplot(
    x=df_clean["Total DL (Bytes)"]
)

plt.title("Boxplot of Total Download")

plt.show()

"""**For all important numeric variables:**"""

for col in numeric_columns[:10]:

    plt.figure(figsize=(8,4))

    sns.boxplot(
        x=df_clean[col]
    )

    plt.title(f"Boxplot - {col}")

    plt.show()

"""**Categorical Analysis**"""

top10_handsets = (
    df_clean["Handset Type"]
    .value_counts()
    .head(10)
)

print(top10_handsets)

"""**Plot**:"""

plt.figure(figsize=(10,6))

top10_handsets.sort_values().plot(
    kind="barh"
)

plt.title("Top 10 Handsets")

plt.xlabel("Number of Users")

plt.show()

"""**Top 3 Manufacturers**"""

top3_manufacturers = (
    df_clean["Handset Manufacturer"]
    .value_counts()
    .head(3)
)

top3_manufacturers

"""**Plot:**"""

plt.figure(figsize=(8,5))

top3_manufacturers.plot(
    kind="bar"
)

plt.title("Top 3 Handset Manufacturers")

plt.ylabel("Count")

plt.show()

"""**Top 5 Handsets per Manufacturer**"""

top_manufacturers = (
    df_clean["Handset Manufacturer"]
    .value_counts()
    .head(3)
    .index
)

for manufacturer in top_manufacturers:

    print("\nManufacturer:", manufacturer)

    result = (
        df_clean[
            df_clean["Handset Manufacturer"]
            == manufacturer
        ]["Handset Type"]
        .value_counts()
        .head(5)
    )

    print(result)

"""**Create User-Level Aggregation**:

**number of xDR sessions**

**session duration**

**total download**

**total upload**

**application data**
"""

user_overview = (
    df_clean
    .groupby("MSISDN/Number")
    .agg(
        xDR_Sessions=("MSISDN/Number", "size"),
        Session_Duration=("Dur. (ms)", "sum"),
        Total_DL=("Total DL (Bytes)", "sum"),
        Total_UL=("Total UL (Bytes)", "sum")
    )
    .reset_index()
)

"""**Add total traffic:**"""

user_overview["Total_Traffic"] = (
    user_overview["Total_DL"] +
    user_overview["Total_UL"]
)

user_overview.head()

"""**Application Traffic**"""

applications = {
    "Social Media": [
        "Social Media DL (Bytes)",
        "Social Media UL (Bytes)"
    ],

    "Google": [
        "Google DL (Bytes)",
        "Google UL (Bytes)"
    ],

    "Email": [
        "Email DL (Bytes)",
        "Email UL (Bytes)"
    ],

    "YouTube": [
        "Youtube DL (Bytes)",
        "Youtube UL (Bytes)"
    ],

    "Netflix": [
        "Netflix DL (Bytes)",
        "Netflix UL (Bytes)"
    ],

    "Gaming": [
        "Gaming DL (Bytes)",
        "Gaming UL (Bytes)"
    ],

    "Other": [
        "Other DL (Bytes)",
        "Other UL (Bytes)"
    ]
}

"""**Now calculate user-level application traffic:**"""

for app, cols in applications.items():

    app_total = (
        df_clean
        .groupby("MSISDN/Number")[cols]
        .sum()
        .sum(axis=1)
    )

    user_overview = user_overview.merge(
        app_total.rename(
            f"{app}_Data"
        ),
        left_on="MSISDN/Number",
        right_index=True,
        how="left"
    )

"""**Application Total Traffic**"""

application_summary = []

for app, cols in applications.items():

    dl = df_clean[cols[0]].sum()

    ul = df_clean[cols[1]].sum()

    total = dl + ul

    application_summary.append([
        app,
        dl,
        ul,
        total
    ])

application_summary = pd.DataFrame(
    application_summary,
    columns=[
        "Application",
        "Download",
        "Upload",
        "Total_Traffic"
    ]
)

application_summary = (
    application_summary
    .sort_values(
        "Total_Traffic",
        ascending=False
    )
)

application_summary

"""**Application Traffic Plot**"""

plt.figure(figsize=(10,6))

sns.barplot(
    data=application_summary,
    x="Application",
    y="Total_Traffic"
)

plt.xticks(rotation=35)

plt.title(
    "Total Traffic by Application"
)

plt.show()

"""**Bivariate Analysis**"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=user_overview,
    x="Gaming_Data",
    y="Total_Traffic",
    alpha=0.3
)

plt.title(
    "Gaming Traffic vs Total Traffic"
)

plt.xlabel("Gaming Traffic")

plt.ylabel("Total Traffic")

plt.show()

"""**Correlation**"""

application_columns = [
    "Social Media_Data",
    "Google_Data",
    "Email_Data",
    "YouTube_Data",
    "Netflix_Data",
    "Gaming_Data",
    "Other_Data"
]

correlation_matrix = (
    user_overview[
        application_columns
    ]
    .corr()
)

correlation_matrix

"""**Heatmap**"""

plt.figure(figsize=(10,8))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title(
    "Application Traffic Correlation Heatmap"
)

plt.show()

"""**Decile Analysis**"""

user_overview["Duration_Decile"] = pd.qcut(
    user_overview["Session_Duration"],
    10,
    labels=False
) + 1

decile_analysis = (
    user_overview
    .groupby("Duration_Decile")
    .agg(
        Users=("MSISDN/Number","count"),
        Total_Duration=("Session_Duration","sum"),
        Total_Traffic=("Total_Traffic","sum")
    )
    .reset_index()
)

decile_analysis

"""**PCA : Prepare application data**"""

X = user_overview[
    application_columns
]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
pca = PCA()

X_pca = pca.fit_transform(
    X_scaled
)
explained_variance = (
    pca.explained_variance_ratio_
    * 100
)

print(explained_variance)

"""**Plot**:"""

plt.figure(figsize=(8,5))

plt.plot(
    range(1, len(explained_variance)+1),
    explained_variance,
    marker="o"
)

plt.xlabel("Principal Component")

plt.ylabel("Explained Variance (%)")

plt.title(
    "PCA Explained Variance"
)

plt.show()

"""**Engagement Analysis**

1.**Session Frequenc**y

2.**Session Duration**

3.**Total Traffic**
"""

engagement = user_overview[
    [
        "MSISDN/Number",
        "xDR_Sessions",
        "Session_Duration",
        "Total_Traffic"
    ]
].copy()

"""**Normalize Engagement Metrics**"""

engagement_features = [
    "xDR_Sessions",
    "Session_Duration",
    "Total_Traffic"
]

scaler = StandardScaler()

engagement_scaled = scaler.fit_transform(
    engagement[
        engagement_features
    ]
)

"""**K-Means k=3**"""

kmeans_engagement = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

engagement["Engagement_Cluster"] = (
    kmeans_engagement
    .fit_predict(engagement_scaled)
)

engagement[
    "Engagement_Cluster"
].value_counts()

"""**Engagement Cluster Summary**"""

engagement_cluster_summary = (
    engagement
    .groupby("Engagement_Cluster")[
        engagement_features
    ]
    .agg([
        "min",
        "max",
        "mean",
        "sum"
    ])
)

engagement_cluster_summary

"""**Elbow Method**"""

inertia = []

for k in range(2, 8):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    model.fit(
        engagement_scaled
    )

    inertia.append(
        model.inertia_
    )

    plt.figure(figsize=(8,5))

plt.plot(
    range(2,8),
    inertia,
    marker="o"
)

plt.xlabel("Number of Clusters")

plt.ylabel("Inertia")

plt.title(
    "Elbow Method for Engagement"
)

plt.show()

"""**User Experience**"""

df_clean["TCP_Retransmission"] = (
    df_clean["TCP DL Retrans. Vol (Bytes)"] +
    df_clean["TCP UL Retrans. Vol (Bytes)"]
) / 2

"""**# RTT:**"""

df_clean["RTT"] = (
    df_clean["Avg RTT DL (ms)"] +
    df_clean["Avg RTT UL (ms)"]
) / 2

"""**Throughput:**"""

df_clean["Throughput"] = (
    df_clean["Avg Bearer TP DL (kbps)"] +
    df_clean["Avg Bearer TP UL (kbps)"]
) / 2

"""**Experience per Customer**"""

experience = (
    df_clean
    .groupby("MSISDN/Number")
    .agg(
        Average_TCP=(
            "TCP_Retransmission",
            "mean"
        ),

        Average_RTT=(
            "RTT",
            "mean"
        ),

        Average_Throughput=(
            "Throughput",
            "mean"
        ),

        Handset_Type=(
            "Handset Type",
            lambda x: x.mode()[0]
        )
    )
    .reset_index()
)

"""**Experience K-Means**"""

experience_features = [
    "Average_TCP",
    "Average_RTT",
    "Average_Throughput"
]

"""Note: **Because lower TCP/RTT and higher throughput generally represent different directions, prepare the clustering features carefully.**"""

experience_model = experience[
    experience_features
].copy()
experience_model["Average_TCP"] *= -1
experience_model["Average_RTT"] *= -1

experience_scaled = StandardScaler().fit_transform(
    experience_model
)

"""**K-Means:**"""

kmeans_experience = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

experience["Experience_Cluster"] = (
    kmeans_experience
    .fit_predict(experience_scaled)
)

"""**Satisfaction**

1.**Engagement Score**; Euclidean distance between the user's data point and the less-engaged cluster.
"""

engagement_centers = (
    kmeans_engagement
    .cluster_centers_
)

least_engaged_cluster = np.argmin(
    engagement_centers.mean(axis=1)
)

least_engaged_cluster

engagement["Engagement_Score"] = np.linalg.norm(
    engagement_scaled -
    engagement_centers[
        least_engaged_cluster
    ],
    axis=1
)

"""**Experience Score**"""

experience_centers = (
    kmeans_experience
    .cluster_centers_
)

worst_experience_cluster = np.argmin(
    experience_centers.mean(axis=1)
)

experience["Experience_Score"] = np.linalg.norm(
    experience_scaled -
    experience_centers[
        worst_experience_cluster
    ],
    axis=1
)

"""**Satisfaction Score**: Merge the two scores"""

satisfaction = engagement[
    [
        "MSISDN/Number",
        "Engagement_Score"
    ]
].merge(
    experience[
        [
            "MSISDN/Number",
            "Experience_Score"
        ]
    ],
    on="MSISDN/Number"
)

satisfaction["Satisfaction_Score"] = (
    satisfaction["Engagement_Score"] +
    satisfaction["Experience_Score"]
) / 2

"""**Top 10 Satisfied Customers**"""

top10_satisfied = (
    satisfaction
    .nlargest(
        10,
        "Satisfaction_Score"
    )
)

top10_satisfied

"""**Satisfaction K-Means k=2**"""

satisfaction_features = satisfaction[
    [
        "Engagement_Score",
        "Experience_Score"
    ]
]

sat_scaled = StandardScaler().fit_transform(
    satisfaction_features
)

kmeans_satisfaction = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

satisfaction["Satisfaction_Cluster"] = (
    kmeans_satisfaction
    .fit_predict(sat_scaled)
)

"""**Satisfaction Cluster Summary**"""

satisfaction_cluster_summary = (
    satisfaction
    .groupby(
        "Satisfaction_Cluster"
    )[
        [
            "Engagement_Score",
            "Experience_Score",
            "Satisfaction_Score"
        ]
    ]
    .mean()
)

satisfaction_cluster_summary

"""**Regression Model**"""

model_data = (
    engagement[
        [
            "MSISDN/Number",
            "xDR_Sessions",
            "Session_Duration",
            "Total_Traffic"
        ]
    ]
    .merge(
        experience[
            [
                "MSISDN/Number",
                "Average_TCP",
                "Average_RTT",
                "Average_Throughput"
            ]
        ],
        on="MSISDN/Number",
        how="inner"
    )
    .merge(
        satisfaction[
            [
                "MSISDN/Number",
                "Satisfaction_Score"
            ]
        ],
        on="MSISDN/Number",
        how="inner"
    )
)

print("model_data created successfully")
print(model_data.shape)
print(model_data.columns.tolist())

print(model_data.columns.tolist())

features = [
    "xDR_Sessions",
    "Session_Duration",
    "Total_Traffic",
    "Average_TCP",
    "Average_RTT",
    "Average_Throughput"
]

X = model_data[features]
y = model_data["Satisfaction_Score"]
print("X shape:", X.shape)
print("y shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    HistGradientBoostingRegressor
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np
import pandas as pd

models = {

    "Linear Regression": LinearRegression(),

    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ),

    "Extra Trees": ExtraTreesRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    ),

    "Hist Gradient Boosting": HistGradientBoostingRegressor(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,
        random_state=42
    )
}

results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    mae = mean_absolute_error(
        y_test,
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_test,
            predictions
        )
    )

    r2 = r2_score(
        y_test,
        predictions
    )

    results.append([
        name,
        mae,
        rmse,
        r2
    ])

model_comparison = pd.DataFrame(
    results,
    columns=[
        "Model",
        "MAE",
        "RMSE",
        "R2"
    ]
)

model_comparison.sort_values(
    "R2",
    ascending=False
)

"""Note: Linear Regression produced a negative R² and performed poorly on the test set. Nonlinear tree-based models substantially improved the results, with Hist Gradient Boosting achieving the highest observed R² of 0.067 in the current comparison.

The regression models showed limited predictive power for the constructed satisfaction score. The nonlinear models performed substantially better than Linear Regression, but the relatively low R² indicates that the available predictor variables do not fully explain variation in the satisfaction score."
"""

print(satisfaction.columns.tolist())

final_satisfaction = satisfaction[
    [
        "MSISDN/Number",
        "Engagement_Score",
        "Experience_Score",
        "Satisfaction_Score"
    ]
].copy()

final_satisfaction.head(10)

print("Rows:", final_satisfaction.shape[0])
print("Columns:", final_satisfaction.shape[1])

print(final_satisfaction.isnull().sum())

print(
    "Duplicate user IDs:",
    final_satisfaction["MSISDN/Number"].duplicated().sum()
)

"""MySQL"""

!pip install pymysql sqlalchemy

final_satisfaction.to_csv(
    "satisfaction_table.csv",
    index=False
)

print("CSV created successfully!")

from google.colab import files

files.download("satisfaction_table.csv")

final_table = satisfaction[
    [
        "MSISDN/Number",
        "Engagement_Score",
        "Experience_Score",
        "Satisfaction_Score",
        "Satisfaction_Cluster"
    ]
]

final_table.to_excel(
    "final_user_scores.xlsx",
    index=False
)

"""**MODEL TRACKING**

**Import required libraries**
"""

import pandas as pd
import numpy as np
import joblib
import json
from datetime import datetime

"""**Select your final model**"""

from sklearn.ensemble import HistGradientBoostingRegressor

final_model = HistGradientBoostingRegressor(
    max_iter=200,
    learning_rate=0.05,
    max_leaf_nodes=31,
    random_state=42
)

start_time = datetime.now()

print("Model training started:", start_time)

final_model.fit(X_train, y_train)

final_pred = final_model.predict(X_test)

"""**Calculate final metrics**"""

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

final_mae = mean_absolute_error(
    y_test,
    final_pred
)

final_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        final_pred
    )
)

final_r2 = r2_score(
    y_test,
    final_pred
)

print("MAE :", final_mae)
print("RMSE:", final_rmse)
print("R²  :", final_r2)

end_time = datetime.now()

print("Model training ended:", end_time)

joblib.dump(
    final_model,
    "satisfaction_model.pkl"
)

print("Model saved successfully!")

tracking_record = pd.DataFrame([{
    "Model_Name": "Hist Gradient Boosting",
    "Version": "v1.0",
    "Start_Time": start_time,
    "End_Time": end_time,
    "Source": "TellCo Telecom User Analytics",
    "Parameters": str(final_model.get_params()),
    "MAE": final_mae,
    "RMSE": final_rmse,
    "R2": final_r2,
    "Artifact": "satisfaction_model.pkl"
}])

tracking_record

tracking_record.to_csv(
    "model_tracking.csv",
    index=False
)

print("Model tracking file created!")

"""**This satisfies the tracking information requested in the brief:**

Model name       → Hist Gradient Boosting

Version          → v1.0

Start time       → recorded

End time         → recorded

Parameters       → recorded

MAE              → recorded

RMSE             → recorded

R²               → recorded

Artifact         → satisfaction_model.pkl

**CREATE FINAL OUTPUT FILES**
"""

import os

os.makedirs("outputs", exist_ok=True)
os.makedirs("outputs/plots", exist_ok=True)

user_overview.to_csv(
    "outputs/user_overview.csv",
    index=False
)

engagement.to_csv(
    "outputs/engagement.csv",
    index=False
)

experience.to_csv(
    "outputs/experience.csv",
    index=False
)

satisfaction.to_csv(
    "outputs/satisfaction.csv",
    index=False
)

model_comparison.to_csv(
    "outputs/model_comparison.csv",
    index=False
)

tracking_record.to_csv(
    "outputs/model_tracking.csv",
    index=False
)

print("All output files saved!")

"""outputs/


├── user_overview.csv

├── engagement.csv

├── experience.csv

├── satisfaction.csv

├── model_comparison.csv

└── model_tracking.csv

**CREATE FINAL EXCEL**
"""

info = pd.DataFrame({
    "Column": df_clean.columns,
    "Data_Type": df_clean.dtypes.astype(str).values,
    "Non_Null_Count": df_clean.notnull().sum().values,
    "Missing_Count": df_clean.isnull().sum().values
})

info["Missing_Percentage"] = (
    info["Missing_Count"] / len(df_clean) * 100
)

info

print(type(info))
print(info.shape)

"""**Check your other Excel variables**"""

variables = [
    "info",
    "missing_report",
    "outlier_df",
    "univariate",
    "top10_handsets",
    "top3_manufacturers",
    "user_overview",
    "application_summary",
    "correlation_matrix",
    "decile_analysis",
    "engagement",
    "experience",
    "satisfaction",
    "model_comparison"
]

for variable in variables:
    print(
        variable,
        "✓" if variable in globals() else "❌ NOT FOUND"
    )

with pd.ExcelWriter(
    "TellCo_Final_Analysis.xlsx",
    engine="openpyxl"
) as writer:

    info.to_excel(
        writer,
        sheet_name="Data_Info",
        index=False
    )

    missing_report.to_excel(
        writer,
        sheet_name="Missing_Values",
        index=False
    )

    outlier_df.to_excel(
        writer,
        sheet_name="Outliers",
        index=False
    )

    univariate.to_excel(
        writer,
        sheet_name="Univariate",
        index=True
    )

    top10_handsets.to_frame("Count").to_excel(
        writer,
        sheet_name="Top10_Handsets"
    )

    top3_manufacturers.to_frame("Count").to_excel(
        writer,
        sheet_name="Top3_Manufacturers"
    )

    user_overview.to_excel(
        writer,
        sheet_name="User_Overview",
        index=False
    )

    application_summary.to_excel(
        writer,
        sheet_name="Applications",
        index=False
    )

    correlation_matrix.to_excel(
        writer,
        sheet_name="Correlation"
    )

    decile_analysis.to_excel(
        writer,
        sheet_name="Deciles",
        index=False
    )

    engagement.to_excel(
        writer,
        sheet_name="Engagement",
        index=False
    )

    experience.to_excel(
        writer,
        sheet_name="Experience",
        index=False
    )

    satisfaction.to_excel(
        writer,
        sheet_name="Satisfaction",
        index=False
    )

    model_comparison.to_excel(
        writer,
        sheet_name="Regression",
        index=False
    )

    tracking_record.to_excel(
        writer,
        sheet_name="Model_Tracking",
        index=False
    )

print("✅ Final Excel created!")

from google.colab import files

files.download("TellCo_Final_Analysis.xlsx")

"""**STREAMLIT DASHBOARD**"""

!pip install streamlit

print("Engagement columns:")
print(engagement.columns.tolist())

print("Experience columns:")
print(experience.columns.tolist())

print("Satisfaction columns:")
print(satisfaction.columns.tolist())

cluster_counts = (
    engagement["Engagement_Cluster"]
    .value_counts()
    .sort_index()
)

cluster_counts = (
    experience["Experience_Cluster"]
    .value_counts()
    .sort_index()
)

engagement["Engagement_Cluster"].nunique()

experience["Experience_Cluster"].nunique()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# st.set_page_config(
#     page_title="TellCo Telecom Analytics",
#     page_icon="📱",
#     layout="wide"
# )
# 
# st.title("📱 TellCo Telecom User Analytics")
# 
# st.write("Telecom User Overview, Engagement, Experience and Satisfaction Analysis")

import os

print(os.path.exists("app.py"))

"""**Dashboard**"""

if page == "Dashboard":

    st.header("Executive Dashboard")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric(
        "Total Users",
        user_overview["MSISDN/Number"].nunique()
    )

    col2.metric(
        "Total Sessions",
        len(user_overview)
    )

    col3.metric(
        "Engagement Clusters",
        engagement["Engagement_Cluster"].nunique()
    )

    col4.metric(
        "Experience Clusters",
        experience["Experience_Cluster"].nunique()
    )

    st.subheader("Top Handsets")

    if "Handset Type" in user_overview.columns:

        handset_count = (
            user_overview["Handset Type"]
            .value_counts()
            .head(10)
        )

        st.bar_chart(handset_count)

"""**User Engagement**"""

if page == "Dashboard":

    st.header("Executive Dashboard")

    # Dashboard code here


elif page == "User Overview":

    st.header("User Overview Analysis")

    # User Overview code here


elif page == "User Engagement":

    st.header("User Engagement Analysis")

    cluster_counts = (
        engagement["Engagement_Cluster"]
        .value_counts()
        .sort_index()
    )

    st.bar_chart(cluster_counts)


elif page == "User Experience":

    st.header("User Experience Analysis")

    cluster_counts = (
        experience["Experience_Cluster"]
        .value_counts()
        .sort_index()
    )

    st.bar_chart(cluster_counts)

"""**User Experience**"""

if page == "Dashboard":

    st.title("📊 TellCo Telecom User Analytics Dashboard")

    st.write("Welcome to the TellCo User Analytics Dashboard.")

elif page == "User Overview":

    st.subheader("👥 User Overview")

    st.metric(
        "Total Users",
        user_overview["MSISDN/Number"].nunique()
    )

elif page == "User Engagement":

    st.subheader("📈 User Engagement")

    st.metric(
        "Engagement Clusters",
        engagement["Engagement_Cluster"].nunique()
    )

    st.bar_chart(
        engagement["Engagement_Cluster"].value_counts()
    )

elif page == "User Experience":

    st.subheader("📶 User Experience")

    st.metric(
        "Experience Clusters",
        experience["Experience_Cluster"].nunique()
    )

    st.bar_chart(
        experience["Experience_Cluster"].value_counts()
    )

elif page == "User Satisfaction":

    st.subheader("😊 User Satisfaction")

    st.metric(
        "Satisfaction Clusters",
        satisfaction["Satisfaction_Cluster"].nunique()
    )

    st.bar_chart(
        satisfaction["Satisfaction_Cluster"].value_counts()
    )

elif page == "Model Results":

    st.subheader("🤖 Model Results")

    st.dataframe(model_comparison)

"""**TESTING**"""

import pandas as pd
import numpy as np


def test_dataframe_not_empty():

    df = pd.DataFrame({
        "A": [1, 2, 3],
        "B": [4, 5, 6]
    })

    assert len(df) > 0


def test_no_missing_values():

    df = pd.DataFrame({
        "A": [1, 2, 3],
        "B": [4, 5, 6]
    })

    assert df.isnull().sum().sum() == 0


def test_satisfaction_calculation():

    engagement = 2.0
    experience = 4.0

    satisfaction = (
        engagement + experience
    ) / 2

    assert satisfaction == 3.0

"""These are simple tests demonstrating the testing structure.

**Main insights included**

*   150,001 records and 55 original columns
*   After cleaning: 0 missing values and 0 duplicate records

*   Apple, Samsung and Huawei are the leading manufacturers
*   Huawei B528S-23A is the most frequent handset type


*   Gaming and Other generate the highest application traffic
*   Application variables show extremely high correlation

*   PCA: first component explains approximately 99.996% variance
*   Engagement: 3 clusters, including one extreme single-user cluster

*   Experience: 3 clusters based on TCP retransmission, RTT and throughput
*   Satisfaction: 2 clusters, with a very strong outlier effect

*   Final model: Hist Gradient Boosting
*   Final metrics: MAE 0.02229, RMSE 1.93562, R² 0.06704

*   Important limitation: the low R² indicates limited predictive power of the available predictors for the constructed satisfaction score.
"""